var json_DOTTIDE_5 = {
"type": "FeatureCollection",
"name": "DOTTIDE_5",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Agency_Name": "Department of Transport", "Agency_Code": "DOT", "Program_Name": "Coastal Data", "Program_Code": "Tide", "Tag": "DOT-TIDE", "Data_File_Name": "FFFBH01_Tidal_Height.csv", "Data_File_Location": "data-warehouse/csv/dot/tide", "Status": "Active", "Lat": -32.06554, "Lon": 115.74807, "Time_Zone": "GMT +8", "Vertical_Datum": "LWM Fremantle 1949 which is 2.752m below Benchmark DMH 098", "Station_ID": "FFFBH01", "Site_Description": "Fremantle Fishing Boat Harbour Tide Station", "Deployment": "Fixed", "Deployment_Position": "m from Datum", "Vertical_Reference": "m from Datum", "Site_Mean_Depth": null, "Bad_Data_Code": -9999.0, "Email": "tides@transport.wa.gov.au", "Variable_ID": "var00180", "DataCategory": "Hydrodynamics", "Sampling_Rate": 5.4048, "Date_Format": "yyyy-mm-dd HH:MM:SS", "Depth_Format": "Decimal", "Variable_Name": "Water Surface Height (m)", "QC_Code": "String", "X": 381828.29969000001, "Y": 6451613.8524900004, "calc_SMD": 0.0, "mAHD": 0.0 }, "geometry": { "type": "Point", "coordinates": [ 115.748067, -32.065543 ] } },
{ "type": "Feature", "properties": { "Agency_Name": "Department of Transport", "Agency_Code": "DOT", "Program_Name": "Coastal Data", "Program_Code": "Tide", "Tag": "DOT-TIDE", "Data_File_Name": "HLHIL01_Tidal_Height.csv", "Data_File_Location": "data-warehouse/csv/dot/tide", "Status": "Inactive", "Lat": -31.82552, "Lon": 115.73859, "Time_Zone": "GMT +8", "Vertical_Datum": "Chart Datum which is 4.895m below Benchmark Hamersley", "Station_ID": "HLHIL01", "Site_Description": "Hillarys", "Deployment": "Fixed", "Deployment_Position": "m from Datum", "Vertical_Reference": "m from Datum", "Site_Mean_Depth": null, "Bad_Data_Code": -9999.0, "Email": "tides@transport.wa.gov.au", "Variable_ID": "var00180", "DataCategory": "Hydrodynamics", "Sampling_Rate": 16.3519, "Date_Format": "yyyy-mm-dd HH:MM:SS", "Depth_Format": "Decimal", "Variable_Name": "Water Surface Height (m)", "QC_Code": "String", "X": 380623.60223000002, "Y": 6478210.58091, "calc_SMD": 2.1545, "mAHD": -2.1545 }, "geometry": { "type": "Point", "coordinates": [ 115.738589, -31.825522 ] } },
{ "type": "Feature", "properties": { "Agency_Name": "Department of Transport", "Agency_Code": "DOT", "Program_Name": "Coastal Data", "Program_Code": "Tide", "Tag": "DOT-TIDE", "Data_File_Name": "PTBAR02_Tidal_Height.csv", "Data_File_Location": "data-warehouse/csv/dot/tide", "Status": "Active", "Lat": -31.95968, "Lon": 115.85726, "Time_Zone": "GMT +8", "Vertical_Datum": "LWM Fremantle which is 2.234m below Benchmark MWB 1484", "Station_ID": "PTBAR02", "Site_Description": "Barrack Street 02 Tide Station", "Deployment": "Fixed", "Deployment_Position": "m from Datum", "Vertical_Reference": "m from Datum", "Site_Mean_Depth": null, "Bad_Data_Code": -9999.0, "Email": "tides@transport.wa.gov.au", "Variable_ID": "var00180", "DataCategory": "Hydrodynamics", "Sampling_Rate": 6.8165, "Date_Format": "yyyy-mm-dd HH:MM:SS", "Depth_Format": "Decimal", "Variable_Name": "Water Surface Height (m)", "QC_Code": "String", "X": 392011.81498999998, "Y": 6463463.2818, "calc_SMD": -1.0, "mAHD": 1.0 }, "geometry": { "type": "Point", "coordinates": [ 115.857261, -31.959681 ] } },
{ "type": "Feature", "properties": { "Agency_Name": "Department of Transport", "Agency_Code": "DOT", "Program_Name": "Coastal Data", "Program_Code": "Tide", "Tag": "DOT-TIDE", "Data_File_Name": "RKMGL01_Tidal_Height.csv", "Data_File_Location": "data-warehouse/csv/dot/tide", "Status": "Inactive", "Lat": -32.27443, "Lon": 115.70334, "Time_Zone": "GMT +8", "Vertical_Datum": "Chart datum which is 2.527m below Benchmark DMH 073", "Station_ID": "RKMGL01", "Site_Description": "Mangles Bay", "Deployment": "Fixed", "Deployment_Position": "m from Datum", "Vertical_Reference": "m from Datum", "Site_Mean_Depth": null, "Bad_Data_Code": -9999.0, "Email": "tides@transport.wa.gov.au", "Variable_ID": "var00180", "DataCategory": "Hydrodynamics", "Sampling_Rate": 9.0831, "Date_Format": "yyyy-mm-dd HH:MM:SS", "Depth_Format": "Decimal", "Variable_Name": "Water Surface Height (m)", "QC_Code": "String", "X": 377885.59739000001, "Y": 6428407.1276700003, "calc_SMD": 1.1698, "mAHD": -1.1698 }, "geometry": { "type": "Point", "coordinates": [ 115.703344, -32.274431 ] } }
]
}
