var json_DPIRDCRP_6 = {
"type": "FeatureCollection",
"name": "DPIRDCRP_6",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Agency_Name": "Department of Primary Industry and Regional Development", "Agency_Code": "DPIRD", "Program_Name": "Crab Research Program", "Program_Code": "CRP", "Tag": "DPIRD-CRP", "Data_File_Name": "D:\\csiem\\data-warehouse\\csv\\dpird\\crp\\DPIRD_JBM_TEMPERATURE_Fixed_DATA.csv", "Data_File_Location": "data-warehouse/csv/dpird/crp", "Status": "Inactive", "Lat": -32.18988, "Lon": 115.77125, "Time_Zone": "GMT +8", "Vertical_Datum": "mAHD", "Station_ID": "JBM", "Site_Description": "South Jervois Bay Port Marker", "Deployment": "Fixed", "Deployment_Position": "1m from Surface", "Vertical_Reference": "m from Surface", "Site_Mean_Depth": null, "Email": null, "Variable_ID": "var00007", "DataCategory": "Water Quality (PhysChm)", "Sampling_Rate": 80.6981, "Date_Format": "yyyy-mm-dd HH:MM:SS", "Depth_Format": "Decimal", "Variable_Name": "Temperature (C)", "QC_Code": "String", "X": 384174.14182000002, "Y": 6437855.1930799996, "calc_SMD": 12.872, "mAHD": -12.872 }, "geometry": { "type": "Point", "coordinates": [ 115.771252, -32.189883 ] } },
{ "type": "Feature", "properties": { "Agency_Name": "Department of Primary Industry and Regional Development", "Agency_Code": "DPIRD", "Program_Name": "Crab Research Program", "Program_Code": "CRP", "Tag": "DPIRD-CRP", "Data_File_Name": "D:\\csiem\\data-warehouse\\csv\\dpird\\crp\\DPIRD_MBS_TEMPERATURE_Fixed_DATA.csv", "Data_File_Location": "data-warehouse/csv/dpird/crp", "Status": "Inactive", "Lat": -32.27121, "Lon": 115.70879, "Time_Zone": "GMT +8", "Vertical_Datum": "mAHD", "Station_ID": "MBS", "Site_Description": "Blue Lagoon Mussels Barge", "Deployment": "Fixed", "Deployment_Position": "1m from Surface", "Vertical_Reference": "m from Surface", "Site_Mean_Depth": null, "Email": null, "Variable_ID": "var00007", "DataCategory": "Water Quality (PhysChm)", "Sampling_Rate": 59.895, "Date_Format": "yyyy-mm-dd HH:MM:SS", "Depth_Format": "Decimal", "Variable_Name": "Temperature (C)", "QC_Code": "String", "X": 378394.59638, "Y": 6428770.6185299996, "calc_SMD": 2.4617, "mAHD": -2.4617 }, "geometry": { "type": "Point", "coordinates": [ 115.708794, -32.271208 ] } },
{ "type": "Feature", "properties": { "Agency_Name": "Department of Primary Industry and Regional Development", "Agency_Code": "DPIRD", "Program_Name": "Crab Research Program", "Program_Code": "CRP", "Tag": "DPIRD-CRP", "Data_File_Name": "D:\\csiem\\data-warehouse\\csv\\dpird\\crp\\DPIRD_NAJ_TEMPERATURE_Fixed_DATA.csv", "Data_File_Location": "data-warehouse/csv/dpird/crp", "Status": "Inactive", "Lat": -32.17579, "Lon": 115.68043, "Time_Zone": "GMT +8", "Vertical_Datum": "mAHD", "Station_ID": "NAJ", "Site_Description": "Garden Island Navy Ammunition Jetty", "Deployment": "Fixed", "Deployment_Position": "1m from Surface", "Vertical_Reference": "m from Surface", "Site_Mean_Depth": null, "Email": null, "Variable_ID": "var00007", "DataCategory": "Water Quality (PhysChm)", "Sampling_Rate": 55.7432, "Date_Format": "yyyy-mm-dd HH:MM:SS", "Depth_Format": "Decimal", "Variable_Name": "Temperature (C)", "QC_Code": "String", "X": 375593.53392999998, "Y": 6439315.85635, "calc_SMD": 11.2277, "mAHD": -11.2277 }, "geometry": { "type": "Point", "coordinates": [ 115.680434, -32.175792 ] } }
]
}
