var json_IMOSANMNCTD_13 = {
"type": "FeatureCollection",
"name": "IMOSANMNCTD_13",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Agency_Name": "Integrated Marine Observing System", "Agency_Code": "IMOS", "Program_Name": "amnmprofile", "Program_Code": "amnmprofile", "Tag": "IMOS-ANMN-CTD", "Data_File_Name": "imos_nrsrot_profile_Chlorophyll-a_2010_DATA.csv", "Data_File_Location": "data-warehouse/csv/imos/amnmprofile", "Status": "Inactive", "Lat": -32.0, "Lon": 115.4, "Time_Zone": "GMT +8", "Vertical_Datum": "mAHD", "Station_ID": "NRSROT_PROFILE", "Site_Description": "Rottnest Island", "Deployment": "Profile", "Deployment_Position": "m from Surface", "Vertical_Reference": "Water Surface", "Site_Mean_Depth": null, "Email": null, "Variable_ID": "var00014", "DataCategory": "Water Quality (Nutrient)", "Sampling_Rate": -8.9247, "Date_Format": "yyyy-mm-dd HH:MM:SS", "Depth_Format": "Decimal", "Variable_Name": "Chlorophyll-a (µg/l)", "QC_Code": "String", "X": 348862.77041, "Y": 6458445.8529500002, "calc_SMD": 52.7718, "mAHD": -52.7718 }, "geometry": { "type": "Point", "coordinates": [ 115.4, -32.0 ] } },
{ "type": "Feature", "properties": { "Agency_Name": "Integrated Marine Observing System", "Agency_Code": "IMOS", "Program_Name": "amnmprofile", "Program_Code": "amnmprofile", "Tag": "IMOS-ANMN-CTD", "Data_File_Name": "imos_waca20_ts_Chlorophyll-a_2010_DATA.csv", "Data_File_Location": "data-warehouse/csv/imos/amnmprofile", "Status": "Inactive", "Lat": -31.9833, "Lon": 115.2276, "Time_Zone": "GMT +8", "Vertical_Datum": "mAHD", "Station_ID": "WACA20_PROFILE", "Site_Description": "WA Canyon 200m", "Deployment": "Profile", "Deployment_Position": "m from Surface", "Vertical_Reference": "Water Surface", "Site_Mean_Depth": null, "Email": null, "Variable_ID": "var00014", "DataCategory": "Water Quality (Nutrient)", "Sampling_Rate": 14.95, "Date_Format": "yyyy-mm-dd HH:MM:SS", "Depth_Format": "Decimal", "Variable_Name": "Chlorophyll-a (µg/l)", "QC_Code": "String", "X": 332545.19788, "Y": 6460043.2311100001, "calc_SMD": 210.0, "mAHD": -210.0 }, "geometry": { "type": "Point", "coordinates": [ 115.2276, -31.9833 ] } }
]
}
