var json_WWMSP22Light_18 = {
"type": "FeatureCollection",
"name": "WWMSP22Light_18",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Agency_Name": "Western Australian Marine Science Institution", "Agency_Code": "WAMSI", "Program_Name": "WAMSI Westport Marine Science Program", "Program_Code": "WWMSP2.2", "Tag": "WWMSP2.2-Light", "Data_File_Name": "D:\\csiem\\data-warehouse\\csv\\wamsi\\wwmsp2.2_light\\wwmsp2_KwinanaShelf_Daily_Photosynthetically_Active_Photon_Flux_DATA.csv", "Data_File_Location": "data-warehouse/csv/wamsi/wwmsp2.2_light", "Status": "Static", "Lat": -32.19771, "Lon": 115.74725, "Time_Zone": "GMT +8", "Vertical_Datum": "mAHD", "Station_ID": "KwinanaShelf", "Site_Description": "KwinanaShelf", "Deployment": "Fixed", "Deployment_Position": "0m above Seabed", "Vertical_Reference": "m above Seabed", "Site_Mean_Depth": 4.5, "Email": null, "Variable_ID": "var00318", "DataCategory": "Light", "Sampling_Rate": 15.0307, "Date_Format": "yyyy-mm-dd HH:MM:SS", "Depth_Format": "Decimal", "Variable_Name": "Daily Photosynthetically Active Photon Flux (µmol/m2/day)", "QC_Code": "String", "X": 381921.5875, "Y": 6436961.4054100001, "calc_SMD": 4.9707, "mAHD": -4.9707 }, "geometry": { "type": "Point", "coordinates": [ 115.74725, -32.19771 ] } },
{ "type": "Feature", "properties": { "Agency_Name": "Western Australian Marine Science Institution", "Agency_Code": "WAMSI", "Program_Name": "WAMSI Westport Marine Science Program", "Program_Code": "WWMSP2.2", "Tag": "WWMSP2.2-Light", "Data_File_Name": "D:\\csiem\\data-warehouse\\csv\\wamsi\\wwmsp2.2_light\\wwmsp2_KwinanaShelf_shade_Daily_Photosynthetically_Active_Photon_Flux_DATA.csv", "Data_File_Location": "data-warehouse/csv/wamsi/wwmsp2.2_light", "Status": "Static", "Lat": -32.19771, "Lon": 115.74725, "Time_Zone": "GMT +8", "Vertical_Datum": "mAHD", "Station_ID": "KwinanaShelf_shade", "Site_Description": "KwinanaShelf_shade", "Deployment": "Fixed", "Deployment_Position": "0m above Seabed", "Vertical_Reference": "m above Seabed", "Site_Mean_Depth": 4.5, "Email": null, "Variable_ID": "var00318", "DataCategory": "Light", "Sampling_Rate": 17.2337, "Date_Format": "yyyy-mm-dd HH:MM:SS", "Depth_Format": "Decimal", "Variable_Name": "Daily Photosynthetically Active Photon Flux (µmol/m2/day)", "QC_Code": "String", "X": 381921.5875, "Y": 6436961.4054100001, "calc_SMD": 4.9707, "mAHD": -4.9707 }, "geometry": { "type": "Point", "coordinates": [ 115.74725, -32.19771 ] } }
]
}
